settings:
  #################   DATASET CONFIG   ###################

  project_name: ""    # also the folder name of the dataset that under ./data folder
  train_imgs: 
  val_imgs: 
  test_imgs: 
  train_anns: 
  val_anns: 

  obj_list: [
    'Background',                       #Background
  ]


  #################   TRAINING CONFIG   ###################
  
  model_name: 'efficientdet-d4' #[efficientdet-d{i} (0-7) | fasterrcnn-{backbone} | yolov4-p{i} (5,7)]

  #pretrained_backbone: './weights/pretrained/pretrained_fold0_d4.pth'                  # Pretrained backbone
  
  gpu_devices: '1'                     # supports multi-gpus
  num_epochs: 100
  batch_size: 1
  num_workers: 4

  fusion_mode: 'nms'                  # Post-process method [nms | wbf | None]
  min_iou_val:  0.5                     # IOU threshold for validation
  min_conf_val: 0.01                    # Confidence score threshold for validation
  max_images_val: 10000                 # max number of images for validation
  
  image_size: [1024,1024]               # should be square to prevent bugs [512, 640, 768, 896, 1024, 1280, 1280, 1536, 1536]
  keep_ratio: False                     # whether to use resize padding

  cutmix: True
  mixup: True

  # learning rate policy
  lr_policy:
    name: "adam"                         #[adam|sgd]
    lr: 0.005                            #[adam: 1e-3 | sgd: 1e-2]
    momentum: 0.937
    weight_decay: 0.0005

  lr_scheduler:
    name: "cosine"                      #[plateau | cosine | 1cycle-yolo | 1cycle]
                                        # if need to specify more scheduler arguments, do it here

  # gradient accumulation
  mixed_precision: True                # whether to use nvidia apex
  total_accumulate_steps: 64          # step * batch_size, not use if equal 0

  # Test time augmentation
  tta: False                             # whether to use TTA while validation
  tta_ensemble_mode: "wbf"              # ensemble method when TTA
  tta_conf_threshold: 0.01
  tta_iou_threshold: 0.9